name: MacOS

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew update && brew install samba
      - name: Build
        run: cargo build --all-features
      - name: Clippy
        run: cargo clippy --features find -- -Dwarnings
